name: just_waveform_example
description: Demonstrates how to use the just_waveform plugin.

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  path: ^1.8.0
  path_provider: ^2.0.0

  just_waveform:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  # disable-swift-package-manager: true
  uses-material-design: true

  assets:
    - audio/
